name: Main
version: the plugin's version
author: the author's name
main: de.pasiteur.EscapeFromPasiteur.Main
api-version: 1.15.2
website: duhurensohn.de
commands:
  help:
    description: describe your command it will appear with /help
    usage: how is the commands' syntax5