name: the plugins name as it should appear in the plugin list /pl
version: the plugin's version
author: the author's name
main: your main class were the onEnable and onDisable methods are. (Ex: org.spigotmc.tutorial.Tutorial)
api-version: the version of the API you want to use, currently only 1.13 is special
depend: tell the server that an external plugin must be loaded before your plugin can be loaded
website: your website appear with /version <pluginname>
commands:
  help:
    description: describe your command it will appear with /help
    usage: how is the commands' syntax