name: EscapeFromPasiteur
version: 88
author: Adolf Hitler
main: de.pasiteur.EscapeFromPasiteur.Main
api-version: 1.13
website: duhurensohn.de
commands:
  help:
    description: describe your command it will appear with /help
  hello:
    description: stupid