name: Main
version: the plugin's version
author: the author's name
main: de.pasiteur.EscapeFromPasiteur.Main
api-version: the version of the API you want to use, currently only 1.13 is special
website: duhurensohn.de
commands:
  help:
    description: describe your command it will appear with /help
    usage: how is the commands' syntax5